version: '3.7'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: gamestone-frontend
    image: gamestone-frontend-dev:0.0.1
    tty: true
    stdin_open: true
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules: